### 第9章 异常
#### 9.1 Java的异常体系

Java程序在运行时可能遇到特殊情况导致出错，为此Java定义了一套完整的异常体系。Java中的异常体系从Throwable类衍生而来，Throwable继承自Object，是所有异常的顶级父类，它有两个重要子类：Error和Exception。

1. **Error**

程序运行时的“特殊情况”分两种：程序员可处理和无法处理的问题。程序员无法处理的问题称为错误（Error） ，它表示系统级错误，是Java运行环境内部错误或硬件问题，由Java虚拟机抛出，遇到此类错误，程序除退出运行别无选择，如OutOfMemoryError（内存溢出）、NoClassDefFoundError（类未定义）、NoSuchMethodError（找不到方法）等。

2. **Exception**

Exception表示异常，是程序需捕捉、处理的“特殊情况”，通常因程序设计不完善产生。Java中的异常主要分为受检异常（Checked Exception ）和非受检异常（Unchecked Exception ）。
    - **受检异常**：
    
    强制要求程序员在代码中处理的异常，不处理则代码无法编译，用于提醒开发者对特定异常进行显式处理，如FileNotFoundException（找不到文件）。
    
    - **非受检异常**：
    
    一般是运行时异常，继承自RuntimeException，编写代码时无需显式捕获，不捕获会在运行期中断程序执行，如NullPointerException（空指针异常）、IndexOutOfBoundsException（数组越界异常）、NumberFormatException（数字转换异常）等。

#### 9.2 和异常有关的关键字

Java中异常处理包括声明异常、抛出异常、捕获异常和处理异常等过程，重点介绍前3个过程。

1. **声明异常**

用throws关键字声明方法可能抛出的异常信息，声明但不处理。如`public void method() throws Exception{// 方法体}`，表示method方法可能抛出Exception异常，由调用者处理。

2. **抛出异常**

throws用于声明可能有异常，throw用于明确抛出异常。在方法体中，如`public void method() throws Exception{throw new Exception();}` 。异常抛出后需处理，处理方式有自己处理和向上抛给调用者处理。若是受检异常，向上抛需再次声明异常；非受检异常则无需再次声明。

3. **捕获异常**

自己处理异常前需先捕获，Java中用try、catch、finally等关键字捕获异常。

    - **try**：指定预防异常的程序块。
    
    - **catch**：紧跟try块后，指定捕获异常的类型。
    
    - **finally**：确保不管异常状况如何都执行的代码块。

try是
必需的，catch和finally至少有一个。如`try{// 代码块}catch(异常类型 异常对象){// 异常处理}finally{// 一定会执行的代码}` ，且try和finally只能有一个，catch可以有多个，可同时捕获多个异常。

#### 9.3 异常链

异常链是将捕获的异常包装进新异常并重新抛出的处理方式（原异常保存为新异常属性） ，可得知异常发生全过程。Java的Throwable类定义了`public Throwable(String message, Throwable cause);`和`public Throwable(Throwable cause);` 构造方法支持异常链传递。如`try{// 代码块}catch(Exception1 e1){throw new Exception2(e1);}` ，处理Exception2时可知它由Exception1引起。

#### 9.4 异常处理的最佳实践

1. **不要使用异常来控制业务逻辑**：业务逻辑分支应用if - else控制，用异常控制逻辑不易理解和维护。

![image](https://github.com/user-attachments/assets/e3b1297d-4f75-4ee5-b2b0-ff3c17a20808)


2. **如果处理不了，请不要捕获**：只捕获能处理的异常，处理不了就向上抛，捕获后不处理无意义，如`try{}catch (Exception e){throw e;}` 。

![image](https://github.com/user-attachments/assets/6a3eb764-821f-4940-9105-12ff225d8f94)


3. **在catch语句中不要使用printStackTrace()**：开发工具常自动生成此语句，它只是把异常信息输出到控制台而非日志，只适用于调试阶段，线上运行时错误信息应通过日志输出。

![image](https://github.com/user-attachments/assets/9ecd96c6-5599-4238-ab4e-7e2823058283)


4. **二次抛出异常时，要带上异常链**：先捕获再抛出新异常时，要带上被捕获异常信息，避免丢失堆栈信息，如`try{}catch (Exception e){// 错误用法throw new MyException();// 正确用法throw new MyException(e);}` 。

![image](https://github.com/user-attachments/assets/1b25e183-2114-4fca-a5c2-e9767ab184f9)



5. **在需要的地方声明特定的受检异常**：受检异常要求调用者处理，可在特殊情况需调用者关注时使用，起提醒作用。

受检异常最大的特点就是要求调用者必须明确的处理这个异常，这其实是一种强制性的约束，所以当代码当中有一些特殊的情况需要让调用者必须关注的时候，要使用受检异常，起到提醒的作用的



6. **异常捕获的顺序需要特殊注意**：捕获多个异常时，要把范围小的异常放前面，RuntimeException、Exception和Throwable的捕获放最后，否则后面特定异常可能无法捕获。

7. **可以直接捕获Exception，但是要注意场景**：一般不建议直接捕获Exception、Throwable，因其捕获范围大，但在微服务RPC接口调用场景，为避免异常抛给外部系统，可能需捕获Exception。

8. **可以直接捕获Throwable，但是要注意场景**：Throwable有Error和Exception子类，一般不建议捕获Error，但提供RPC服务时，若服务调用发生Error（如NoSuchMethodError ） ，不捕获会被RPC框架捕获，可能导致错误日志不在应用业务日志中，此时可能需捕获。 

9. **不要在finally中抛出异常**：在finally中抛出异常会丢失原异常信息，给问题排查带来困难，如`try {execute();}finally{throw new Exception();}` 。

10. **在finally中释放资源**：释放数据库链接、文件链接等资源应在finally中进行，因其代码必定执行。

11. **如果不想处理异常，则使用finally块而不是catch块**：不想处理异常又想在异常发生后做些事，应使用finally块，而非写无用的catch块。

12. **善于使用自定义异常**：可创建继承Exception子类的异常类实现自定义异常，构建业务异常体系，如在下单交易应用中定义SystemException、BusinessException等，还可在异常中定义成员变量（如错误码、错误信息 ） ，错误码常用枚举类型。

13. **try块中的代码要尽可能的少**：控制try的粒度，不要把明显不会发生异常的代码放try块中。

不要再一个几百行的代码外面添加一个try进行异常处理，我们需要控制try的粒度

![image](https://github.com/user-attachments/assets/c486a655-6e40-4454-b3ab-5867ed9700f4)

![image](https://github.com/user-attachments/assets/66980214-deef-461c-88fc-ade9462661e6)

![image](https://github.com/user-attachments/assets/b81c26f2-313f-435a-b577-89b1d0e9bed1)

![image](https://github.com/user-attachments/assets/cbb0390a-1273-43f4-a8f4-091bd5dc20a6)



#### 9.5 自定义异常
Java异常体系完善且内置很多异常，但常需自定义异常传递信息。创建继承Exception子类的异常类可实现自定义异常，如定义重复调用异常、参数校验错误异常等。业务中常通过继承构建异常体系，如在下单交易应用中，定义SystemException和BusinessException作为基类，再基于它们扩展ExternalSystemException、DbException等。有时在异常中定义成员变量（如错误码、错误信息 ） ，错误码常用枚举类型，如`public class PriceCalculateException extends Exception {private PricingCalculateErrorCode pricingCalculateErrorCode;}` 。 


### 9.5 自定义异常
Java的异常体系非常完善，Java中也内置了很多异常，但很多时候我们需要自定义一些异常，以便更好地传递异常信息。

我们只需要创建一个异常类，并且继承Exception的子类就可以实现一个自定义异常。

我们可以自定义很多业务异常，如重复调用异常、参数校验错误异常、库存不足异常、余额扣减失败异常等。

通常在业务中我们会通过继承关系来构建异常体系，比如在一个处理下单交易的应用中，我们可能构建出来的异常体系如下：

```java
SystemException extends RuntimeException{}
BusinessException extends RuntimeException{}
```

SystemException表示系统异常，BusinessException表示业务异常，这两个异常是整个应用中异常体系的基类，所有其他的自定义异常基于这两个类进行扩展。

```java
ExternalSystemException extends SystemException{}
TimeoutException extends ExternalSystemException{}
DbException extends SystemException{}
ConnectFailedException extends DbException{}
```

基于系统异常，我们又可以定义外部系统异常ExternalSystemException和数据库异常DbException等，外部系统异常又可以定义超时异常TimeoutException，数据库异常又可以定义连接失败异常ConnectFailedException等。

以上通过继承的方式，可以针对自己的应用系统定义一套异常体系。

有时为了让异常中可以传达出更多、更准确的信息，我们会在异常中定义一些成员变量，比如错误码、错误信息等。

因为这些错误码通常都是设定好的，所以一般情况下可以使用枚举类型：

```java
public class PriceCalculateException extends Exception {
    private PricingCalculateErrorCode pricingCalculateErrorCode;
}
```

```java
public PriceCalculateException(PricingCalculateErrorCode pricingCalculateErrorCode,
                               String message) {
    super(message);
    this.pricingCalculateErrorCode = pricingCalculateErrorCode;
}

public PriceCalculateException(PricingCalculateErrorCode pricingCalculateErrorCode,
                               Exception e) {
    super(e);
    this.pricingCalculateErrorCode = pricingCalculateErrorCode;
}

public PriceCalculateException(PricingCalculateErrorCode pricingCalculateErrorCode) {
    super(pricingCalculateErrorCode.name());
    this.pricingCalculateErrorCode = pricingCalculateErrorCode;
}

public PricingCalculateErrorCode getPricingCalculateErrorCode() {
    return pricingCalculateErrorCode;
}
```

这样我们可以在需要抛出异常的地方使用`throw`抛出一个明确的异常：

```java
throw new PriceCalculateException(PricingCalculateErrorCode.QUERY_PRICE_CONFIG_FAILED);
```

基于异常体系，下面介绍在开发中一个比较好的实践，主要用到了自定义异常、自定义错误码、自定义断言等。

首先，定义一个接口，表示一种具有解释性的错误码，提供两个方法，用于返回错误码和错误描述信息。

```java
/**
 * 可解释的通用错误码
 * @author Hollis
 */
public interface ExplicableErrorCode {
    /**
     * 获取描述信息
     * @return
     */
    public String getMsg();

    /**
     * 返回错误码
     * @return
     */
    public String getCode();
}
```
我们基于这个接口，就可以自定义一些错误码信息了。我们可以针对贷款管理业务定义贷款管理相关的错误码枚举：


```java
/**
 * @author Hollis
 */
public enum LoanManageErrorCode implements ExplicableErrorCode {
    /**
     * 还款本金金额大于剩余本金金额
     */
    REPAY_PRINCIPAL_IS_GREATER_THAN_PRINCIPAL("repay principal (%) is greater than rest principal  (%)"),
    /**
     * 剩余本金为负
     */
    REST_PRINCIPAL_IS_NEGATIVE("rest principal (%) is negative");

    LoanManageErrorCode(String msg) {
        this.msg = msg;
    }

    private String msg;

    @Override
    public String getMsg() {
        return msg;
    }

    @Override
    public String getCode() {
        return this.name();
    }
}
```

接下来，我们自定义一个通用异常，异常中有一个成员变量，就是我们刚才定义的`ExplicableErrorCode`，并且还提供了一个数组类型的参数列表`args`：

```java
/**
 * 通用异常
 * @author Hollis
 */
public class BaseException extends RuntimeException {
    protected ExplicableErrorCode errorCode;
    protected Object[] args;

    public BaseException() {
    }

    public BaseException(ExplicableErrorCode errorCode, Object... args) {
        this.args = args;
        this.errorCode = errorCode;
    }

    public BaseException(ExplicableErrorCode errorCode) {
        this.errorCode = errorCode;
    }

    public ExplicableErrorCode getErrorCode() {
        return errorCode;
    }

    public String getErrorMsg() {
        if (errorCode == null) {
            return null;
        }
        return String.format(errorCode.getMsg(), this.args);
    }

    @Override
    public String toString() {
        return new StringJoiner(", ")
              .add("[" + this.getClass().getSimpleName() + "]")
              .add("ErrorCode=[" + errorCode + "]")
              .add("Msg=[" + String.format(errorCode.getMsg(), this.args) + "]")
              .toString();
    }

    @Override
    public String getMessage() {
        return toString();
    }
}
```

这个`toString`方法将异常中的错误码及错误信息打印出来了，这样异常被抛出时，就可以明确地看到错误信息了。

基于通用异常，可以自定义更多的业务异常，如针对贷款管理业务定义的贷款管理异常：

```java
/**
 * 资产管理异常
 *
 * @author Hollis
 */
public class LoanManageException extends BaseException {
    public LoanManageException() {
        super();
    }

    public LoanManageException(ExplicableErrorCode errorCode, Object... args) {
        super(errorCode, args);
    }

    public LoanManageException(ExplicableErrorCode errorCode) {
        super(errorCode);
    }
}
```
这样我们就可以在代码中使用如下方式抛出一个异常：
```java
throw new LoanManageException(LoanManageErrorCode.REPAY_PRINCIPAL_IS_GREATER_THAN_PRINCIPAL, 10, 20);
```
这个异常在被捕获之后，当`toString`方法被调用时，就会打印以下内容：
```
[LoanManageException], ErrorCode=[REPAY_PRINCIPAL_IS_GREATER_THAN_PRINCIPAL], Msg=[repay principal (10) is greater than rest principal  (20)]
```
这样更加方便我们排查问题。

为了方便我们使用自定义的异常，还可以对其进行更深层次的封装，例如：
```java
public class LoanManageAssert {
    public static void isTrue(boolean expression, LoanManageErrorCode errorCode, Object... args) {
        if (!expression) {
            throw new LoanManageException(errorCode, args);
        }
    }

    public static void isEquals(Integer num1, Integer num2, LoanManageErrorCode errorCode) {
        if (num1.compareTo(num2) != 0) {
            throw new LoanManageException(errorCode, num1, num2);
        }
    }

    public static void isLessThanOrEqualTo(Integer num1, Integer num2, LoanManageErrorCode errorCode) {
        if (num1.compareTo(num2) <= 0) {
            throw new LoanManageException(errorCode, num1, num2);
        }
    }
}
```
我们自定义了一个`LoanManageAssert`类，这个类中定义了一系列的断言方法，比如判断表达式结果是否为`true`、判断两个数是否相等。

当断言失败时，自动抛出`LoanManageException`。

有了以上这些层次的封装，我们在编写业务代码时就非常方便了，例如：

```java
Integer paidPrincipal = tradeRepayEvent.getPaidPrincipal().get();
LoanManageAssert.isLessThanOrEqualTo(paidPrincipal, principal,
        LoanManageErrorCode.REPAY_PRINCIPAL_IS_GREATER_THAN_PRINCIPAL);
```

这样就可以减少很多`if-else`的逻辑判断，只需要通过断言工具类，对我们想要强校验的地方进行断言处理即可。一旦断言失败，就会抛出固定的`LoanManageException`，并且错误码是我们自己指定的。

以上代码中抛出了一个`LoanManageException`，我们如何处理它呢？一般会统一地处理这种业务异常，所以我们还可以再实现一个工具类：

```java
public class ResponseProcessor {
    private static final Logger logger = LoggerFactory.getLogger(ResponseProcessor.class);
    public static <T, R extends BaseResponse> R handle(T request, R response, String method,
                                                         Function<T, R> function) {
        try {
            logger.info("before execute method={}, request={}", method, DesensitizeUtils.desens(request));
            requireNonNull(request);
            BeanValidator.validateObject(request);
            response = function.apply(request);
            if (response.getResponseCode() == null) {
                response.setResponseCode(CommonResponseCode.SUCCESS.name());
            }
            return response;
        } catch (LoanManageException e) {
            logger.error(e.toString(), e);
            response.setSuccess(false);
            response.setResponseCode(e.getErrorCode().getCode());
            response.setResponseMessage(e.getErrorMsg());
        } catch (IllegalArgumentException e) {
            logger.error(e.getMessage(), e);
            response.setSuccess(false);
            response.setResponseCode(CommonResponseCode.ILLEGAL_ARGUMENT.name());
            response.setResponseMessage(e.getMessage());
        } catch (Throwable e) {
            logger.error(e.getMessage(), e);
            response.setSuccess(false);
            response.setResponseCode(CommonResponseCode.SYSTEM_ERROR.name());
            response.setResponseMessage(e.getMessage());
        } finally {
            logger.info("after method={}, request = {}, response = {}", method, request, response);
        }
        return response;
    }
}
```
以上代码自定义了一个`ResponseProcessor`，用来对一次方法调用进行包装，在调用过程中，如果抛出`LoanManageException`，就会被捕获，捕获之后就会统一打印日志，并对`response`进行失败处理。用法也比较简单：

```java
return responseProcessor.handle(request, response, "responseProcessor.handle", req -> {
    // 方法体
});
```

### 9.6 try-with-resources

在Java中，对于文件操作的I/O流、数据库连接等开销非常大的资源，用完之后必须及时通过`close`方法将其关闭，否则资源会一直处于打开状态，可能导致内存泄漏等问题。

关闭资源的常用方式就是在`finally`块中进行处理，即调用`close`方法。比如，我们经常会写这样的代码：

```java
public static void main(String[] args) {
    BufferedReader br = null;
    try {
        String line;
        br = new BufferedReader(new FileReader("d:\\ hollischuang.xml"));
        while ((line = br.readLine()) != null) {
            System.out.println(line);
        }
    } catch (IOException e) {
        // handle exception
    } finally {
        try {
            if (br != null) {
                br.close();
            }
        } catch (IOException ex) {
            // handle exception
        }
    }
}
```

从Java 7开始，JDK提供了一种更好的关闭资源的方式，即使用`try-with-resources`语句。改写一下上面的代码，效果如下：

```java
public static void main(String... args) {
    try (BufferedReader br = new BufferedReader(new FileReader("d:\\ hollischuang.xml"))) {
        String line;
        while ((line = br.readLine()) != null) {
            System.out.println(line);
        }
    } catch (IOException e) {
        // handle exception
    }
}
```
虽然笔者之前一般使用`IOUtils`去关闭流，并不会使用在`finally`中写很多代码的方式，但这种新的语法糖看上去更优雅。其实现源码如下：
```java
public static transient void main(String args[]) {
    BufferedReader br;
    Throwable throwable;
    br = new BufferedReader(new FileReader("d:\\ hollischuang.xml"));
    throwable = null;
    String line;
    try {
        while ((line = br.readLine()) != null)
            System.out.println(line);
    } catch (Throwable throwable2) {
        throwable = throwable2;
        throw throwable2;
    }
    if (br != null)
        if (throwable != null)
            try {
                br.close();
            } catch (Throwable throwable1) {
                throwable.addSuppressed(throwable1);
            }
        else
            br.close();
    break MISSING_BLOCK_LABEL_113;
    Exception exception;
    exception;
    if (br != null)
        if (throwable != null)
            try {
                br.close();
            } catch (Throwable throwable3) {
                throwable.addSuppressed(throwable3);
            }
        else
            br.close();
    throw exception;
    IOException ioexception;
    ioexception;
}
```

实现原理也很简单，那些我们没有做的关闭资源的操作，编译器都帮我们做了。所以再次印证了，语法糖的作用就是方便程序员的使用，“含糖代码”最终还是要转成编译器认识的语言。

### 9.7 finally是在什么时候执行的

我们知道，`finally`的代码一定会被执行，那么：它是在什么时间点执行的呢？比如以下代码，`test()`的返回结果应该是多少？

```java
public int test() {
    int a = 1;
    try {
        return a + 1;
    } finally {
        a = 2;
    }
}
```
以上代码的输出结果为2。
如果在`finally`中也加一个`return`：
```java
public int get() {
    int a = 1;
    try {
        return a;
    }
}
```

```java
} finally {
    a = 2;
    return a;
}
```
以上代码的输出结果为2。

虽然`finally`代码会执行，但是在`return`后面的表达式运算后执行的，所以函数返回值是在`finally`执行前就确定了。

也就是说，`finally`中的代码会在`a + 1`计算之后、`return`执行返回操作之前执行。

如果在`finally`中也有`return`语句，那么方法就会提前返回，而返回的结果就是`finally`中`return`的值。

不知道读者会不会有这样的问题：如果在`try/catch`块中，JVM突然中断了（比如使用`System.exit(0)`），那么`finally`中的代码还会执行吗？

比如以下代码：
```java
public void print() {
    try {
        System.out.println("try");
        System.exit(0);
    } finally {
        System.out.println("finally");
    }
}
```
输出结果为`try`。

`finally`的执行需要两个前提条件：对应的`try`语句块被执行；程序正常运行。

当使用`System.exit(0)`中断执行时，`finally`就不会再执行了。 
